### ISSUE TITLE
Module(s) not found

### ISSUE THREAD

**Issue by Zloka** [anubra266/chakra-remix-stack-blues#1]
Hi! I wanted to try out the stack, but the `postinstall` script was outputting some errors. The following modules were reportedly not found (in order):

- stylis
- hoist-non-react-statics
- warning
- @chakra-ui/theme-tools 
- @chakra-ui/styled-system

Installing each separately and then running `npm install` again seems to work, but I figured I'd leave a note of this here 🙂

**Comment by anubra266** [comment]
Thanks @Zloka did you clone the repo, or you used the `remix` method?

**Comment by Zloka** [comment]
I used the `remix` method, i.e. `npx create-remix --template anubra266/chakra-remix-stack-blues`.

**Comment by Zloka** [comment]
Actually, I noticed now that there is both a `package-lock.json` and `yarn.lock` file. I tried the template from scratch again using `yarn`, and that seems to work just fine 🙂

**Comment by anubra266** [comment]
But I'm not seeing any `package-lock.json` in the repo. @Zloka

**Comment by anubra266** [comment]
I see @Zloka, the problem is the remix cli uses npm for installations by default. I've updated the Readme to avoid this

**Comment by Zloka** [comment]
Ah yeah, true that. Probably stems from that I used `npm` the first time around, as the `CLI` asks about running `npm install`.
